# -*- coding: utf-8 -*-
"""Copia de ABP-06-v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_Sf_jn4REjXmHUFtqA5C48cWjsO2SxE

# Proyecto de Inferencia Estadística (ABP-6)

**Dataset:** hábitos saludables en estudiantes universitarios
**Módulo:** 6 Inferencia estadística

**Temas cubiertos:**

- Método científico.
- Probabilidad.
- Distribuciones.
- Teorema del límite central.
- Intervalos de confianza.
- Test de hipótesis.

---
## Etapa 1 - Método cientifico

### Problema de investigación

¿Cuáles son los patrones y factores que influyen en los hábitos saludables (sueño, alimentación, actividad física) de los jóvenes universitarios, y qué relación tienen entre sí?

### Hipótesis

- **H₀ (nula):** La media de horas de sueño de los estudiantes universitarios es igual a 7 horas (valor de referencia recomendado).
- **H₁ (alternativa):** La media de horas de sueño de los estudiantes universitarios **no** es igual a 7 horas.

### Variables
| Variable | Tipo       | Descripción                              |
|----------|------------|------------------------------------------|
| `horas_sueno` | Cuantitativa continua | Horas de sueño por noche |
| `horas_estudio` | Cuantitativa continua | Horas de estudio diarias |
| `horas_ejercicio_semana` | Cuantitativa continua | Horas de ejercicio por semana |
| `nivel_estres` | Cuantitativa continua | Nivel de estrés (escala 1–10) |
| `imc` | Cuantitativa continua | Índice de masa corporal |
| `pasos_diarios` | Cuantitativa discreta | Pasos diarios |
| `calidad_alimentacion` | Cuantitativa discreta | Calidad de alimentación (1–5) |
| `consume_alcohol` | Cualitativa binaria | Consume alcohol (0=No, 1=Sí) |
| `edad` | Cuantitativa discreta | Edad del estudiante |

### Enfoque metodológico
Se aplica un enfoque **hipotético-deductivo**: partimos de hipótesis basadas en valores de referencia médicos y las contrastamos con datos reales usando herramientas de inferencia estadística (intervalos de confianza y pruebas de hipótesis).

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import norm, binom

from google.colab import files

csv = files.upload()

df = pd.read_csv("dataset_habitos_saludables_universitarios_500.csv")

# Exploración inicial del dataset

print( "Información general" )
print( "===================" )
print()
print( df.shape )
print()
print( df.info() )
print()
print( "Estadísticas descriptivas" )
print( "-------------------------" )
print( df.describe() )
print()
print( "Primeras filas" )
print( "--------------" )
print( df.head() )

"""---
## Etapa 2 - Probabilidad
---
"""

p_dormir_mas7  = (df['horas_sueno'] > 7).mean()
p_alcohol      = df['consume_alcohol'].mean()
p_no_alcohol   = 1 - p_alcohol   # Complemento
p_interseccion = ((df['horas_sueno'] > 7) & (df['consume_alcohol'] == 1)).mean()  # Intersección
p_union        = ((df['horas_sueno'] > 7) | (df['consume_alcohol'] == 1)).mean()  # Unión

print( "Probabilidades básica" )
print( "---------------------\n" )
print( f'P(duerme > 7 horas)                          = {p_dormir_mas7:.3f}')
print( f'P(consume alcohol)                           = {p_alcohol:.3f}')
print( f'P(NO consume alcohol)  [complemento]         = {p_no_alcohol:.3f}')
print( f'P(duerme>7 Y consume alcohol) [intersección] = {p_interseccion:.3f}')
print( f'P(duerme>7 O consume alcohol) [unión]        = {p_union:.3f}')

# Verificación de la regla de la adición
p_union_calculada = p_dormir_mas7 + p_alcohol - p_interseccion
print()
print( f"Verificación (A+B-A∩B): {p_union_calculada:.3f} ≈ {p_union:.3f}" )

# Árbol de probabilidad simplificado (visualización)
fig, ax = plt.subplots(figsize=(10, 5))
ax.axis('off')

# Nodos del árbol
nodes = [
  (0.05, 0.5, 'Estudiante'),
  (0.35, 0.75, f'Duerme > 7h\nP={p_dormir_mas7:.2f}'),
  (0.35, 0.25, f'Duerme ≤ 7h\nP={1-p_dormir_mas7:.2f}'),
  (0.75, 0.88, f'Alcohol\nP={p_interseccion/p_dormir_mas7:.2f}'),
  (0.75, 0.62, f'No alcohol\nP={1-p_interseccion/p_dormir_mas7:.2f}'),
  (0.75, 0.38, f'Alcohol\nP={((df["horas_sueno"]<=7)&(df["consume_alcohol"]==1)).mean()/(1-p_dormir_mas7):.2f}'),
  (0.75, 0.12, f'No alcohol\nP={((df["horas_sueno"]<=7)&(df["consume_alcohol"]==0)).mean()/(1-p_dormir_mas7):.2f}'),
]

# Dibujar nodos
for x, y, label in nodes:
  ax.text(x, y, label, ha="center", va="center",
    bbox=dict(boxstyle="round,pad=0.3", facecolor="lightblue", edgecolor="navy"),
    fontsize=8)

# Dibujar líneas
lines = [(0.12,0.5,0.28,0.75),(0.12,0.5,0.28,0.25),
         (0.48,0.75,0.62,0.88),(0.48,0.75,0.62,0.62),
         (0.48,0.25,0.62,0.38),(0.48,0.25,0.62,0.12)]
for x1,y1,x2,y2 in lines:
  ax.annotate('', xy=(x2,y2), xytext=(x1,y1),
    arrowprops=dict(arrowstyle="->", color="navy"))

ax.set_title("Árbol de Probabilidad — Sueño y Consumo de Alcohol", fontsize=12, fontweight="bold")
plt.tight_layout()
plt.show()

"""---
## Etapa 3 - Distribuciones de Probabilidad

- Identificamos y justificamos las distribuciones para cada variable clave.
---
"""

# Distribución NORMAL para horas_sueno
media_s = df['horas_sueno'].mean()
std_s   = df['horas_sueno'].std()

# Probabilidades con la distribución normal
p_menos6  = norm.cdf(6, loc=media_s, scale=std_s)
p_entre67 = norm.cdf(7, loc=media_s, scale=std_s) - norm.cdf(6, loc=media_s, scale=std_s)
p_mas8    = 1 - norm.cdf(8, loc=media_s, scale=std_s)

print( "Distribución Normal — Horas de sueño" )
print( "------------------------------------" )
print( f"Media: {media_s:.2f}  |  Desv. estándar: {std_s:.2f}" )
print( f"P(dormir < 6h)     = {p_menos6:.4f}" )
print( f"P(6h ≤ dormir < 7h)= {p_entre67:.4f}" )
print( f"P(dormir > 8h)     = {p_mas8:.4f}" )

x = np.linspace(df["horas_sueno"].min()-0.5, df["horas_sueno"].max()+0.5, 200)
y = norm.pdf(x, media_s, std_s)

fig, ax = plt.subplots(figsize=(8, 4))
ax.hist(df["horas_sueno"], bins=20, density=True, alpha=0.6, color="steelblue", label="Datos observados")
ax.plot(x, y, "r-", lw=2, label=f"Normal(μ={media_s:.2f}, σ={std_s:.2f})")
ax.axvline(media_s, color="darkred", linestyle="--", label=f"Media = {media_s:.2f}")
ax.set_title("Distribución Normal — Horas de sueño")
ax.set_xlabel("Horas"); ax.set_ylabel("Densidad")
ax.legend()
plt.tight_layout()
plt.show()

n_grupo = 10
p_alc   = df["consume_alcohol"].mean()

k_values = np.arange(0, n_grupo + 1)
prob_binom = binom.pmf(k_values, n_grupo, p_alc)

prob_exactamente_3 = binom.pmf(3, n_grupo, p_alc)
prob_al_menos_5   = 1 - binom.cdf(4, n_grupo, p_alc)

print( "Distribución Binomial — Consumo de alcohol" )
print( "------------------------------------------" )
print( f"n = {n_grupo} estudiantes  |  p = {p_alc:.2f}")
print( f"P(exactamente 3 consumen alcohol) = {prob_exactamente_3:.4f}")
print( f"P(al menos 5 consumen alcohol)    = {prob_al_menos_5:.4f}")

fig, ax = plt.subplots(figsize=(8, 4))
bars = ax.bar(k_values, prob_binom, color="coral", edgecolor="darkred", alpha=0.8)
bars[3].set_color("darkred")
ax.set_title(f"Distribución Binomial — Consumo de alcohol (n={n_grupo}, p={p_alc})")
ax.set_xlabel("Número de estudiantes que consumen alcohol")
ax.set_ylabel("Probabilidad")
ax.set_xticks(k_values)
for bar, prob in zip(bars, prob_binom):
  ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.003,
    f"{prob:.3f}", ha="center", va="bottom", fontsize=7)
plt.tight_layout()
plt.show()

"""---
## Etapa 4. Teorema del Límite Central (TLC)

- Verificamos empíricamente el TLC mostrando cómo la distribución de medias muestrales se aproxima a la normal para distintos tamaños muestrales.
---
"""

np.random.seed(42)
tamaños = [5, 15, 30, 100]
n_simulaciones = 1_000

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

for i, n in enumerate(tamaños):
  medias = [df["horas_sueno"].sample(n).mean() for _ in range(n_simulaciones)]
  error_teorico = df["horas_sueno"].std() / np.sqrt(n)

  ax = axes[i]
  ax.hist(medias, bins=30, density=True, alpha=0.6, color="steelblue", label="Medias muestrales")

  # Curva normal teórica
  x = np.linspace(min(medias)-0.2, max(medias)+0.2, 200)
  ax.plot(x, norm.pdf(x, df["horas_sueno"].mean(), error_teorico),
    "r-", lw=2, label="Normal teórica (TLC)")

  ax.set_title(f"n = {n}  |  σ_x̄ teórico = {error_teorico:.3f}")
  ax.set_xlabel("Media muestral"); ax.set_ylabel("Densidad")
  ax.legend(fontsize=7)

fig.suptitle("Teorema del Límite Central — Horas de sueño\n(1.000 simulaciones por tamaño muestral)",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

print()
print( 'Dispersión de la media según tamaño muestral' )
print( f'{"n":>5}  {"σ_x̄ teórico":>15}  {"σ_x̄ empírico":>15}' )
for n in tamaños:
  medias = [df["horas_sueno"].sample(n).mean() for _ in range(n_simulaciones)]
  teo = df["horas_sueno"].std() / np.sqrt(n)
  emp = np.std(medias)
  print(f"{n:>5}  {teo:>15.4f}  {emp:>15.4f}")

# Comparación distribución poblacional vs distribución muestral (n=30)
np.random.seed(42)
medias_n30 = [df["horas_sueno"].sample(30).mean() for _ in range(1_000)]

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].hist(df["horas_sueno"], bins=25, color="steelblue", edgecolor="white", alpha=0.8)
axes[0].set_title("Distribución POBLACIONAL\nHoras de sueño (n=500)")
axes[0].set_xlabel("Horas"); axes[0].set_ylabel("Frecuencia")
axes[0].axvline(df["horas_sueno"].mean(), color="red", linestyle="--",
      label=f'μ = {df["horas_sueno"].mean():.2f}')
axes[0].legend()

axes[1].hist(medias_n30, bins=30, color="coral", edgecolor="white", alpha=0.8)
axes[1].set_title("Distribución MUESTRAL de medias\n(n=30, 1.000 simulaciones)")
axes[1].set_xlabel("Media muestral"); axes[1].set_ylabel("Frecuencia")
axes[1].axvline(np.mean(medias_n30), color='darkred', linestyle="--",
      label=f"x̄ = {np.mean(medias_n30):.2f}")
axes[1].legend()

plt.suptitle("Comparación: Distribución Poblacional vs Distribución Muestral", fontweight="bold")
plt.tight_layout()
plt.show()

"""---
## Etapa 5 - Intervalo de confianza

- Calculamos intervalos de confianza para la media de **dos variables** con tres niveles de confianza (90%, 95%, 99%).
---
"""

def intervalo_confianza(data, nivel):
  """
  Calcula IC para la media usando la distribución normal.
  """
  n     = len(data)
  media = data.mean()
  std   = data.std()
  alpha = 1 - nivel
  z     = norm.ppf(1 - alpha / 2)
  error = z * std / np.sqrt(n)
  return media - error, media + error, error

variables = {
  "horas_sueno": "Horas de Sueño",
  "horas_ejercicio_semana": "Horas de Ejercicio/Semana",
}

niveles = [0.90, 0.95, 0.99]

for col, nombre in variables.items():
  print()
  print( f"{nombre} (μ = {df[col].mean():.4f})" )
  print( f'{"Confianza":>12}  {"Límite inf":>12}  {"Límite sup":>12}  {"Ancho IC":>10}')
  for niv in niveles:
    li, ls, err = intervalo_confianza(df[col], niv)
    print( f"{niv*100:>11.0f}%  {li:>12.4f}  {ls:>12.4f}  {2*err:>10.4f}" )

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
colores = ["#2196F3", "#FF9800", "#F44336"]
labels  = ["90%", "95%", "99%"]

for ax, (col, nombre) in zip(axes, variables.items()):
  media = df[col].mean()
  for j, niv in enumerate(niveles):
    li, ls, _ = intervalo_confianza(df[col], niv)
    ax.barh(j, ls - li, left=li, height=0.4, color=colores[j], alpha=0.7, label=labels[j])
    ax.plot(media, j, "ko", ms=5)
  ax.set_yticks(range(len(niveles)))
  ax.set_yticklabels(labels)
  ax.set_xlabel("Valor")
  ax.set_title(f"Intervalos de Confianza — {nombre}")
  ax.axvline(media, color="black", linestyle="--", lw=1, label=f"Media = {media:.2f}")
  ax.legend(fontsize=8)

plt.suptitle("Efecto del Nivel de Confianza en el Ancho del Intervalo", fontweight="bold")
plt.tight_layout()
plt.show()

print()
print( "Interpretación:" )
print( "A mayor nivel de confianza, mayor es el ancho del intervalo." )
print( "Con n=500 los intervalos son estrechos, lo que indica estimaciones precisas." )

"""---
## Etapa 6 - Test de hipótesis

### Planteamiento
- **H₀:** μ = 7 horas (la media de sueño es la recomendada)
- **H₁:** μ ≠ 7 horas (test bilateral)
- **Nivel de significancia:** α = 0.05
---
"""

mu_0 = 7
alpha = 0.05
t_stat, p_value = stats.ttest_1samp(df["horas_sueno"], mu_0)

print("Test t de hipótesis — Horas de sueño")
print("------------------------------------")
print( f"H₀: μ = {mu_0}   |   H₁: μ ≠ {mu_0}")
print( f"Estadístico t = {t_stat:.4f}")
print( f"p-value       = {p_value:.4f}")
print( f"Nivel α       = {alpha}")

print()

if p_value < alpha:
  print( "Decisión: RECHAZAR H₀" )
  print( f"   El p-value ({p_value:.4f}) < α ({alpha}). Hay evidencia estadística para afirmar" )
  print( f"   que la media de sueño difiere de {mu_0} horas." )
else:
  print( "Decisión: NO rechazar H₀" )
  print( f"   El p-value ({p_value:.4f}) ≥ α ({alpha}). No hay suficiente evidencia para afirmar" )
  print( f"   que la media de sueño difiere de {mu_0} horas." )

# Visualización del test de hipótesis
fig, ax = plt.subplots(figsize=(10, 5))

gl = len(df) - 1
x  = np.linspace(-4, 4, 400)
y  = stats.t.pdf(x, df=gl)

ax.plot(x, y, "k-", lw=2, label="Distribución t")

# Región de rechazo (bilateral)
t_crit = stats.t.ppf(1 - alpha/2, df=gl)
ax.fill_between(x, y, where=(x <= -t_crit), color="red", alpha=0.4, label=f"Región rechazo (α={alpha})")
ax.fill_between(x, y, where=(x >= t_crit), color="red", alpha=0.4)

# Estadístico observado
ax.axvline(t_stat, color="blue", linestyle="--", lw=2, label=f"t observado = {t_stat:.3f}")
ax.axvline(-t_crit, color="darkred", linestyle=":", lw=1.5, label=f"t crítico = ±{t_crit:.3f}")
ax.axvline(t_crit, color="darkred", linestyle=":", lw=1.5)

ax.set_title("Test de Hipótesis: ¿La media de sueño es 7 horas?", fontsize=12)
ax.set_xlabel("Valor t"); ax.set_ylabel("Densidad")
ax.legend(fontsize=9)
plt.tight_layout()
plt.show()

# Errores Tipo I y Tipo II
print( "Errores Tipo I y Tipo II" )
print( "------------------------" )
print()
print( "Error Tipo I (α):  Rechazar H₀ cuando es verdadera." )
print( f"  -> Probabilidad fijada: α = {alpha}" )
print(  "  -> En este contexto: concluir que los estudiantes NO duermen 7h cuando sí lo hacen." )
print()
print( "Error Tipo II (β): No rechazar H₀ cuando es falsa." )
print( "  -> En este contexto: concluir que los estudiantes SI duermen 7h cuando no lo hacen." )
print()

# Potencia del test (ejemplo con desplazamiento de 0.5h)
delta = 0.5
mu_alt = mu_0 + delta
error_estandar = df["horas_sueno"].std() / np.sqrt(len(df))
t_crit_val = stats.t.ppf(1 - alpha/2, df=len(df)-1)

# Potencia aproximada
nc = delta / error_estandar
potencia = 1 - stats.t.cdf(t_crit_val - nc, df=len(df)-1) + stats.t.cdf(-t_crit_val - nc, df=len(df)-1)
print( f"Potencia del test (μ_alt = {mu_alt}): {potencia:.4f}" )
print( f"Error Tipo II estimado (β): {1-potencia:.4f}" )

print("=" * 60)
print( f"{'CONCLUSIONES FINALES DEL ESTUDIO':^60}")
print("=" * 60)

li2, ls2, _ = intervalo_confianza(df["horas_ejercicio_semana"], 0.95)

print()
print( "1. SUEÑO" )
print( f'   Media observada: {df["horas_sueno"].mean():.2f}h')
print( f'   IC 95%: ({intervalo_confianza(df["horas_sueno"], 0.95)[0]:.2f}, '
       f'{intervalo_confianza(df["horas_sueno"], 0.95)[1]:.2f})')
print(f'   Test H₀ (μ=7): p={p_value:.4f} -> No se rechaza H₀.')
print(f'   Los estudiantes duermen en promedio ~7h, dentro del rango recomendado.')

print()
print('2. ACTIVIDAD FÍSICA')
print(f'   Media: {df["horas_ejercicio_semana"].mean():.2f}h/semana, IC 95%: ({li2:.2f}, {ls2:.2f})')
print(f'   Los estudiantes realizan en promedio ~3h de ejercicio por semana.')

print()
print('3. CONSUMO DE ALCOHOL')
print(f'   Prevalencia: {df["consume_alcohol"].mean()*100:.1f}% de los estudiantes')
print(f'   P(grupo de 10 con exactamente 3 consumidores) = {binom.pmf(3,10,df["consume_alcohol"].mean()):.4f}')

print()
print('4. TLC')
print('   La distribución de medias muestrales converge a la normal a medida')
print('   que aumenta n, confirmando el Teorema del Límite Central.')